/**
 * Available icon names for the FIcon component
 * Using Feather Icons (https://feathericons.com/) + custom icons
 */
export type IconName =
  // Custom icons
  | 'quote'
  | 'see-more'
  | 'checkmark'
  | 'close'
  | 'star-filled'
  | 'email'
  | 'location'
  | 'crown'
  | 'whatsapp'
  // Feather icons (commonly used subset)
  | 'activity'
  | 'alert-circle'
  | 'alert-triangle'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'award'
  | 'bar-chart'
  | 'bell'
  | 'bookmark'
  | 'calendar'
  | 'camera'
  | 'check'
  | 'check-circle'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'clock'
  | 'copy'
  | 'credit-card'
  | 'download'
  | 'edit'
  | 'edit-2'
  | 'edit-3'
  | 'external-link'
  | 'eye'
  | 'eye-off'
  | 'facebook'
  | 'file'
  | 'filter'
  | 'grid'
  | 'heart'
  | 'home'
  | 'image'
  | 'info'
  | 'instagram'
  | 'link'
  | 'list'
  | 'lock'
  | 'log-in'
  | 'log-out'
  | 'mail'
  | 'map-pin'
  | 'maximize'
  | 'menu'
  | 'message-circle'
  | 'minimize'
  | 'minus'
  | 'moon'
  | 'more-horizontal'
  | 'more-vertical'
  | 'phone'
  | 'phone-call'
  | 'plus'
  | 'refresh-cw'
  | 'save'
  | 'scissors'
  | 'search'
  | 'send'
  | 'settings'
  | 'share'
  | 'share-2'
  | 'shopping-bag'
  | 'shopping-cart'
  | 'star'
  | 'sun'
  | 'tag'
  | 'trash'
  | 'trash-2'
  | 'trending-up'
  | 'twitter'
  | 'upload'
  | 'user'
  | 'users'
  | 'x'
  | 'x-circle'
  | 'zoom-in'
  | 'zoom-out'

/**
 * Icon component props
 */
export interface IconProps {
  /** Icon name */
  name: IconName
  /** Icon size in pixels */
  size?: number
  /** Icon color (CSS color value) */
  color?: string
}
